version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "4000:4000"
    environment:
      - REACT_APP_API_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_PATH=/app/data/database.sqlite
      - FRONTEND_URL=http://frontend:4000
      - SECRET_KEY=123456
    volumes:
      - ./backend/data:/app/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge